**************************************************
C FORTRAN TYPES CONTAINING DORADE DESCRIPTORS 
**************************************************
	TYPE VOLD_INFO
   	   integer*2 ver_num
   	   integer*2 vol_num
	   integer max_bytes
	   character*20 proj_name
	   integer*2 year
	   integer*2 mon
	   integer*2 day
	   integer*2 hour
	   integer*2 min
	   integer*2 sec
	   character*8 flight_num
	   character*8 gen_fac_name
	   integer*2 gen_year
	   integer*2 gen_mon
	   integer*2 gen_day
	   integer*2 num_sensors
	END TYPE
**************************************************
	TYPE RADD_INFO
   	   character*8 rad_name
	   real rad_constant
	   real peak_pow
	   real noise_pos
	   real rec_gain
	   real ant_gain
	   real sys_gain
	   real horiz_beam_width
	   real vert_beam_width
	   integer*2 rad_type
	   integer*2 scan_mode
	   real scan_rate
	   real start_ang
	   real stop_ang
	   integer*2 num_param_desc
	   integer*2 num_desc
	   integer*2 compress_flag
	   integer*2 data_reduc_flag
	   real data_reduc_parm1
	   real data_reduc_parm2
	   real radar_lon
	   real radar_lat
	   real radar_alt
	   real unambig_vel
	   real unambig_range
	   integer*2 num_freq
	   integer*2 num_pulse
	   real freq1
	   real freq2
	   real freq3
	   real freq4
	   real freq5
	   real pulse_per1
	   real pulse_per2
	   real pulse_per3
	   real pulse_per4
	   real pulse_per5
	END TYPE
**************************************************
	TYPE CELV_INFO
	   integer total_gates
	   real gate_spacing(2000)
	END TYPE
**************************************************
	TYPE CFAC_INFO
	   real c_azimuth
	   real c_elevation
	   real c_range_delay
	   real c_rad_lon
	   real c_rad_lat
	   real c_alt_msl
	   real c_alt_agl
	   real c_ew_grspeed
	   real c_ns_grspeed
	   real c_vert_vel
	   real c_head
	   real c_roll
	   real c_pitch
	   real c_drift
	   real c_rotang
	   real c_tiltang
	END TYPE
**************************************************
	TYPE PARM_INFO
	   character*8 parm_name
	   character*40 parm_desc
	   character*8 parm_unit
	   integer*2 ipp
	   integer*2 trans_freq
	   real rec_bandwidth
	   integer*2 pulse_width
	   integer*2 polarization
	   integer*2 num_samples
	   integer*2 parm_type
	   character*8 threshold_fld
	   real threshold_val
	   real scale_fac
	   real offset_fac
	   integer baddata_flag
	END TYPE
**************************************************
	TYPE SWIB_INFO
	   character*8 rad_name
	   integer sweep_num
	   integer num_rays
	   real start_ang
	   real stop_ang
	   real fixed_ang
	   integer filter_flag
	END TYPE
**************************************************
	TYPE RYIB_INFO
	   integer sweep_num
	   integer julian_day
	   integer*2 hour
	   integer*2 min
	   integer*2 sec
	   integer*2 msec
	   real azimuth
	   real elevation
	   real peak_power
	   real scan_rate
	   integer ray_status
	END TYPE
**************************************************
	TYPE ASIB_INFO
	   real lon
	   real lat
	   real alt_msl
	   real alt_agl
	   real ew_gspeed
	   real ns_gspeed
	   real vert_vel
	   real head
	   real roll
	   real pitch
	   real drift
	   real rot_ang
	   real tilt_ang
	   real ew_horiz_wind
	   real ns_horiz_wind
	   real vert_wind
	   real head_change
	   real pitch_change
	END TYPE
**************************************************
	TYPE RDAT_INFO
	   character*8 parm_name
	   real data(2000)
	END TYPE
**************************************************
	TYPE PARM_NAME
           SEQUENCE
	   Integer*2 int(4) 
	   Character*8 name
	END TYPE

