FFLAGS  = -g -fsloppy-char
FC = g95
CC = gcc
NCARG = /usr/local/ncarg
LIB = -L$(NCARG)/lib -I$(NCARG)/include \
	-L/usr/lib/gcc/i386-redhat-linux/3.4.3\
	-L/usr/X11R6/lib -I/usr/X11R6/include  -lncarg \
	-lncarg_gks -lncarg_c -lXpm -lX11 -lXext 

OBJS = VD.o sqrt.o vdinclude.o 
VD: $(OBJS)
	$(FC) -v $(FFLAGS) $(OBJS) $(GLIB) $(LIB) -o $@ 
